---
name: module3_task2
run-name: module3_task2
on:
  push:
    branches:
      - master
  schedule:
    - cron: '15 6 * * *'

defaults:
  run:
    shell: bash
    working-directory: ./module3_task2

jobs:
  create-package:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: ./setup.sh

      - name: lint go source files
        run: make lint

      - name: Build webpage and API
        run: make build

      - name: Validate and lint markdown files
        run: make check && make validate

      - name: Run Unit & Integrations Tests
        run: make test

      - name: Build ZIP file
        run: make package

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./module3_task2/awesome-website.zip
...
