---
name: module3_task2
run-name: Create Package - M3T2
on:
  push:
    branches:
      - master
  schedule:
    - cron: '15 6 * * *'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: module3_task2
        run: ./setup.sh

      - name: lint
        run: make lint

  build:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: module3_task2
        run: ./setup.sh

      - name: Build webpage and API
        run: make build

      - name: Upload Build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            /dist
            awesome-api
  
  testing-style:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: module3_task2
        run: ./setup.sh

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: /dist

      - name: Test style
        run: |
          make check
          make validate

  test-webpage-api:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: module3_task2
        run: ./setup.sh

      - name: Download api
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: awesome-api

      - name: Download web
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: /dist

      - name: Test api
        run: |
          make run
          make test
...
