---

name: module3_task2
on:
  push:
    branches:
      # Execute the workflow on every push to the main branch
      - master
  schedule:
    # Execute the workflow every day at 6:15 am
    - cron: '15 6 * * *'

jobs:
  create-package:
    # The workflow will run on ubuntu-22.04
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd module3_task2 && ./setup.sh

      - name: Most make targets
        working-directory: module3_task2
        run: make lint && make build && make check && \
             make test && make validate && \
             make run && make package && \
             make POST_NAME=name POST_TITLE=title post && \
             make clean

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: API and Webpage Package
          path: module3_task2/awesome-webpage.zip
...
