---
name: module3_task1
run-name: Build - M3T1
on:
  push:
    branches:
      - master
  schedule:
    - cron: '15 6 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: module3_task1
        run: ./setup.sh

      - name: Build
        working-directory: module3_task1
        run: make build
...
