---

name: module3_task3
on:
  push:
    branches:
      # Execute the workflow on every push to the main branch
      - master
    tags:
      - "*"
  schedule:
    # Execute the workflow every day at 6:15 am
    - cron: '15 6 * * *'

jobs:
  upload-release:
    # The workflow will run on ubuntu-22.04
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: module3_task3
        run: ./setup.sh

      - name: Test make actions
        working-directory: module3_task3
        run: |
          make lint
          make check
          make test
          make validate
          make build

      - name: Make package
        working-directory: module3_task3
        run: make run && make package

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: awesome-webpage.zip
          path: module3_task3/awesome-webpage.zip

      - name: GitHub Actions Debugging
        run: ls -la && echo "" && ls -la module3_task3/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            module3_task3/DEPLOY.md
            awesome-webpage.zip
          tag_name: 1.0.0
          body_path: ./module3_task4/DEPLOY.md
...
