---
name: module3_task4
run-name: module3_task4
on:
  push:
    branches:
      - master
    tags:
      - '1.0.*'
  schedule:
    - cron: '15 6 * * *'
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

defaults:
  run:
    working-directory: ./module3_task4

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: ./setup.sh

      - name: lint go source files
        run: make lint

      - name: Build webpage and API
        run: make build

      - name: Validate and lint markdown files
        run: make check && make validate

      - name: Run Unit & Integrations Tests
        run: make test

      - name: Build ZIP file
        run: make package

      - name: Debugging github variables
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Actor is ${{ github.actor }}"
          echo "Event: ${{ github.event }}"
          echo "Sha: ${{ github.sha }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./module3_task4/awesome-website.zip
            ./module3_task4/DEPLOY.md
          body_path: ./module3_task4/DEPLOY.md
          tag_name: '1.0.1'
...
